name: frontend_ci     #name of workflow

on:
  push:   #trriger

jobs:   #define jobs
  build:  
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: toilet-dash
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20.15.1
          cache: npm
          cache-dependency-path: toilet-dash/package-lock.json

      - name: cache-node-modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: toilet-dash/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('toilet-dash/package-lock.json') }}

      - name: npm-install
        run: npm i
      
      - name: app-build
        run: npm run build

      - name: actions-status-discord
        uses: sarisia/actions-status-discord@v1.14.5
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

      - name: firebase-hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with: 
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOILET_DASH_CE2DB }}
          projectId: toilet-dash-ce2db
          entryPoint: "./toilet-dash/"