name: Vercel Build Test

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on: pull_request

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN
      
      - name: Build Project Artifacts
        id: build-test
        run: vercel build --prod --token=$VERCEL_TOKEN | echo "BUILD_STATUS=$?" > "$GITHUB_OUTPUT"

      - name: Create failed comment file
        if: ${{ steps.build-test.outputs.BUILD_STATUS }} != 0
        run: |
          cat  << EOF > comment.md
          ## Test Failed
          The tests failed. Please check the logs for more information.
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          EOF

      - name: Create success comment file
        if: ${{ steps.build-test.outputs.BUILD_STATUS }} == 0
        run: |
          cat  << EOF > comment.md
          ## Test Success
          The tests succeeded.
          EOF

      - name: Make comment
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr comment ${{github.event.pull_request.head.ref}} --body-file comment.md --edit-last || gh pr comment ${{github.event.pull_request.head.ref}} --body-file comment.md